apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment

spec:
  selector:
    matchLabels:
      component: front
  template:
    metadata:
      labels:
        component: front
    spec:
      containers:
        - name: front-container
          image: mo29172/vitecamion_front:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: API_BASE_URL_BROWSER
              valueFrom:
                secretKeyRef:
                  name: front-envs
                  key: API_BASE_URL_BROWSER
            - name: API_BASE_URL_SERVER
              valueFrom:
                secretKeyRef:
                  name: front-envs
                  key: API_BASE_URL_SERVER